apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-page
  template:
    metadata:
      labels:
        app: web-page
    spec:
      containers:
      - name: nginx
        image: registry.local/myapp/web-page:latest
        ports:
        - containerPort: 80
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
