name: Build and Push to Harbor

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Build image
        run: docker build -t 192.168.0.7:30500/myapp/web-page:${{ github.sha }} .
      
      - name: Login to Harbor
        run: echo ${{ secrets.HARBOR_PASSWORD }} | docker login 192.168.0.7:30500 -u admin --password-stdin
      
      - name: Push image
        run: |
          docker push 192.168.0.7:30500/myapp/web-page:${{ github.sha }}
          docker tag 192.168.0.7:30500/myapp/web-page:${{ github.sha }} 192.168.0.7:30500/myapp/web-page:latest
          docker push 192.168.0.7:30500/myapp/web-page:latest
