name: Build and Push to Harbor

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Build image
        run: docker build -t harbor.black2swan.ru/myapp/web-page:${{ github.sha }} .
      
      - name: Login to Harbor
        run: echo ${{ secrets.HARBOR_PASSWORD }} | docker login https://harbor.black2swan.ru -u admin --password-stdin
      
      - name: Push image
        run: |
          docker push harbor.black2swan.ru/myapp/web-page:${{ github.sha }}
          docker tag harbor.black2swan.ru/myapp/web-page:${{ github.sha }} harbor.black2swan.ru/myapp/web-page:latest
          docker push harbor.black2swan.ru/myapp/web-page:latest
